apiVersion: v1
kind: Pod
metadata:
  labels:
    name: test-the-mailserver
  name: test-the-mailserver
spec:
  containers:
    - image: "kristijorgji/test-the-mailserver:0.0.1"
      name: test-the-mailserver
      imagePullPolicy: Always
      volumeMounts:
        - name: config-volume
          mountPath: /usr/src/app/.env
          subPath: .env
  restartPolicy: Never
  volumes:
    - name: config-volume
      configMap:
        name: test-the-mailer-config
        items:
          - key: .env
            path: .env
